import React,{useEffect,useState}from"react";import{createRoot}from"react-dom/client";import"./style.css";
const SPORTS=[["cricket","🏏","Cricket"],["soccer","⚽","Football"],["tennis","🎾","Tennis"],["basketball","🏀","Basketball"]];
const DEMO=[["Cricket","Malaysia","United Arab Emirates"],["Football","North City FC","United Stars"],["Tennis","Player A","Player B"]];
const fmt=n=>Number(n||0).toLocaleString("en-IN");
function App(){const[page,setPage]=useState("home"),[sport,setSport]=useState("cricket"),[events,setEvents]=useState([]),[match,setMatch]=useState(null),[slip,setSlip]=useState([]),[favorites,setFavorites]=useState([]),[token,setToken]=useState(localStorage.getItem("nova")||""),[user,setUser]=useState(null),[auth,setAuth]=useState(false),[search,setSearch]=useState(""),[toast,setToast]=useState("");
useEffect(()=>{if(token)fetch("/api/me",{headers:{Authorization:"Bearer "+token}}).then(r=>r.ok?r.json():null).then(x=>x&&setUser(x.user))},[token]);
useEffect(()=>{load()},[sport]);async function load(){let out=[];try{let ss=await fetch("/api/sports").then(r=>r.ok?r.json():[]);for(let s of ss.filter(x=>x.active&&x.group===sport).slice(0,4)){let r=await fetch("/api/odds/"+s.key+"?markets=h2h,spreads,totals");if(r.ok)out.push(...await r.json())}}catch{}if(!out.length)out=DEMO.filter(x=>x[0].toLowerCase()===(sport==="soccer"?"football":sport)).map((x,i)=>({id:"d"+i,home_team:x[1],away_team:x[2],sport_title:x[0],commence_time:new Date(Date.now()+i*3600000).toISOString(),demo:true,bookmakers:[]}));setEvents(out)}
function add(e,o,m){if(!token){setAuth(true);return}let x={eventId:e.id,eventName:(e.home_team||"")+" vs "+(e.away_team||""),selection:o.name,market:m.key,odds:+o.price};setSlip(a=>[...a.filter(z=>z.eventId!==x.eventId||z.selection!==x.selection),x]);setToast("Added to virtual slip")}
async function coins(){if(!token)return setAuth(true);let r=await fetch("/api/demo-coins",{method:"POST",headers:{Authorization:"Bearer "+token,"Content-Type":"application/json"},body:JSON.stringify({amount:1000})});let d=await r.json();if(r.ok){setUser(d.user);setToast("+1,000 virtual coins")}}
return <><header><button className="logo"onClick={()=>setPage("home")}><b>N</b><span className="brandText">NOVA<span>PLAY</span></span></button><div className="right"><button className="searchMini"onClick={()=>document.getElementById("eventSearch")?.focus()}>⌕</button><button onClick={()=>user?setPage("wallet"):setAuth(true)}>🪙 {fmt(user?.coins||0)}</button><button onClick={()=>user?setPage("profile"):setAuth(true)}>◉</button></div></header>
<main>{page==="home"&&<Home setPage={setPage} sport={sport} setSport={setSport} events={events} open={e=>{setMatch(e);setPage("match")}} add={add} coins={coins} search={search} setSearch={setSearch} favorites={favorites} setFavorites={setFavorites}/>}
{page==="sports"&&<Sports sport={sport}setSport={setSport}events={events}open={e=>{setMatch(e);setPage("match")}}add={add} search={search} setSearch={setSearch} favorites={favorites} setFavorites={setFavorites}/>}
{page==="match"&&<Match e={match}back={()=>setPage("sports")}add={add}/>}
{page==="slip"&&<Slip items={slip}setSlip={setSlip}place={async(x)=>{let r=await fetch("/api/bets",{method:"POST",headers:{"Content-Type":"application/json",Authorization:"Bearer "+token},body:JSON.stringify({...x,stake:100})});let d=await r.json();if(r.ok){setUser(d.user);setSlip(a=>a.filter(z=>z!==x));setToast("Virtual bet placed")}else setToast(d.error)}}/>}
{page==="wallet"&&<Wallet user={user}coins={coins}/>}
{page==="profile"&&<Profile user={user}setPage={setPage}logout={()=>{localStorage.removeItem("nova");setToken("");setUser(null);setPage("home")}}/>}
{page==="history"&&<History token={token}/>} {page==="games"&&<Games/>}</main>
<nav><button onClick={()=>setPage("home")}>⌂<small>Home</small></button><button onClick={()=>setPage("sports")}>◈<small>Sports</small></button><button className="center"onClick={()=>setPage("slip")}>▱<i>{slip.length}</i></button><button onClick={()=>setPage("games")}>◇<small>Games</small></button><button onClick={()=>user?setPage("profile"):setAuth(true)}>♙<small>Account</small></button></nav>
{auth&&<Auth close={()=>setAuth(false)}done={(t,u)=>{localStorage.setItem("nova",t);setToken(t);setUser(u);setAuth(false)}}/>}{toast&&<div className="toast">{toast}</div>}</>}
function Home(p){return <div className="page"><section className="hero"><div><div className="livePill"><i/> LIVE FEED CONNECTED</div><small>WELCOME TO NOVA PLAY</small><h1>Next-level<br/><em>play zone.</em></h1><p>Live sports, smart markets and a premium virtual-coin experience.</p><div className="heroActions"><button className="primary"onClick={()=>p.setPage("sports")}>Explore Sports →</button><button className="ghost"onClick={()=>p.setPage("games")}>Game Lounge</button></div></div><div className="orb">🪙<small>VIRTUAL<br/>ONLY</small></div></section><div className="stats"><div><b>LIVE</b><small>Sports feed</small></div><div><b>4+</b><small>Sports</small></div><div><b>24/7</b><small>Demo access</small></div></div><div className="quick"><button onClick={()=>p.setPage("sports")}>⚡<b>Live Sports</b><small>Real-time feed</small></button><button onClick={()=>p.setPage("games")}>🎮<b>Game Lounge</b><small>Demo games</small></button><button onClick={p.coins}>🎁<b>Daily Coins</b><small>+1,000 demo</small></button></div><div className="searchBox"><span>⌕</span><input id="eventSearch"placeholder="Search teams, players or leagues"value={p.search}onChange={e=>p.setSearch(e.target.value)}/></div><h2>Popular sports</h2><Rail {...p}/><div className="sectionLine"><h2>Live & upcoming</h2><button onClick={()=>p.setPage("sports")}>View all →</button></div><Events {...p}/><div className="note">🛡️ Virtual coins only · No cash value</div></div>}
function Rail({sport,setSport}){return <div className="rail">{SPORTS.map(x=><button className={sport===x[0]?"sel":""}onClick={()=>setSport(x[0])}key={x[0]}>{x[1]} {x[2]}</button>)}</div>}
function Sports(p){return <div className="page"><div className="title"><div><small>SPORTS HUB</small><h1>All markets</h1></div><b>● LIVE</b></div><div className="searchBox"><span>⌕</span><input id="eventSearch"placeholder="Search teams, players or leagues"value={p.search}onChange={e=>p.setSearch(e.target.value)}/></div><Rail {...p}/><div className="filters"><button className="active">All</button><button>Live</button><button>Upcoming</button><button>☆ Favorites</button></div><Events {...p}/></div>}
function Events({events,open,add,search="",favorites=[],setFavorites}){let list=events.filter(e=>`${e.home_team} ${e.away_team} ${e.sport_title}`.toLowerCase().includes(search.toLowerCase()));if(!list.length)return <div className="empty">No matching events right now.</div>;return <div className="events">{list.map(e=>{let m=e.bookmakers?.[0]?.markets?.[0],os=m?.outcomes||[],fav=favorites.includes(e.id);return <article onClick={()=>open(e)}key={e.id}><div className="meta"><span>{e.sport_title||"SPORT"} <i className="liveTiny">●</i></span><button className={fav?"star on":"star"} onClick={v=>{v.stopPropagation();setFavorites&&setFavorites(a=>fav?a.filter(x=>x!==e.id):[...a,e.id])}}>{fav?"★":"☆"}</button></div><div className="teams"><b>{e.home_team}</b><b>{e.away_team}</b><small>{new Date(e.commence_time).toLocaleString("en-IN",{day:"2-digit",month:"short",hour:"2-digit",minute:"2-digit"})}</small></div><div className="odds">{os.slice(0,3).map((o,i)=><button onClick={v=>{v.stopPropagation();add(e,o,m)}}key={i}><small>{o.name}</small><b>{(+o.price).toFixed(2)}</b></button>)}{!os.length&&<span className="soon">Open match for markets →</span>}</div><footer><span>+{Math.max(3,e.bookmakers?.length*3||3)} markets</span><span>Open match →</span></footer></article>})}</div>}
function Match({e,back,add}){const[tab,setTab]=useState("all");let ms=e?.bookmakers?.[0]?.markets||[];if(!e)return null;let shown=tab==="all"?ms:ms.filter(x=>x.key===tab);return <div className="page"><button className="back"onClick={back}>← Back</button><section className="match"><small>{e.sport_title||"SPORT"}</small><h1>{e.home_team}</h1><strong>VS</strong><h1>{e.away_team}</h1><p>{new Date(e.commence_time).toLocaleString("en-IN",{weekday:"short",day:"2-digit",month:"short",hour:"2-digit",minute:"2-digit"})}</p></section><div className="marketTabs"><button className={tab==="all"?"active":""}onClick={()=>setTab("all")}>All</button>{ms.some(x=>x.key==="h2h")&&<button className={tab==="h2h"?"active":""}onClick={()=>setTab("h2h")}>Winner</button>}{ms.some(x=>x.key==="spreads")&&<button className={tab==="spreads"?"active":""}onClick={()=>setTab("spreads")}>Handicap</button>}{ms.some(x=>x.key==="totals")&&<button className={tab==="totals"?"active":""}onClick={()=>setTab("totals")}>Totals</button>}</div>{shown.length?shown.map(m=><Market e={e}m={m}add={add}key={m.key}/>):<div className="empty">Markets will appear when the live provider supplies odds.</div>}<div className="note">Tap any price to add it to your virtual slip.</div></div>}
function Market({e,m,add}){return <section className="market"><header><b>{m.key==="h2h"?"Match Winner":m.key==="spreads"?"Handicap":m.key==="totals"?"Over / Under":m.key}</b><small>VIRTUAL</small></header><div>{m.outcomes.map(o=><button onClick={()=>add(e,o,m)}key={o.name}>{o.name}<b>{(+o.price).toFixed(2)}</b></button>)}</div></section>}
function Slip({items,setSlip,place}){return <div className="page"><div className="title"><div><small>YOUR PICKS</small><h1>Virtual slip</h1></div>{items.length>0&&<button onClick={()=>setSlip([])}>Clear</button>}</div>{!items.length?<div className="empty big">🧾<br/><b>Slip is empty</b><small>Open a match and tap a price.</small></div>:<>{items.map(x=><div className="slip"><div><b>{x.selection}</b><small>{x.eventName}</small></div><strong>{x.odds.toFixed(2)}</strong></div>)}<section className="stake"><b>Stake per pick: 🪙 100</b><button className="primary"onClick={()=>items.forEach(place)}>Place virtual bet</button></section></>}</div>}
function Wallet({user,coins}){return <div className="page"><small>MY WALLET</small><h1>Coin Center</h1><section className="balance"><small>AVAILABLE VIRTUAL COINS</small><h1>🪙 {fmt(user?.coins)}</h1><button className="primary"onClick={coins}>＋ Claim 1,000</button></section><div className="note">No deposits, UPI payments or cash withdrawals are included. Coins have no cash value.</div></div>}
function Profile({user,setPage,logout}){return <div className="page"><div className="profile"><div>{user?.username?.[0]?.toUpperCase()}</div><h1>{user?.username}</h1><small>Virtual-coin member</small></div><div className="menu"><button onClick={()=>setPage("wallet")}>🪙 Coin Center</button><button onClick={()=>setPage("history")}>📜 Bet History</button><button>⭐ Favorites</button><button>⚙️ Settings</button></div><button className="danger"onClick={logout}>Log out</button></div>}
function History({token}){const[a,setA]=useState([]);useEffect(()=>{fetch("/api/bets",{headers:{Authorization:"Bearer "+token}}).then(r=>r.json()).then(x=>setA(x.bets||[]))},[]);return <div className="page"><small>ACCOUNT</small><h1>Bet History</h1>{a.map(x=><div className="history"key={x.id}><b>{x.selection}</b><small>{x.event_name} · 🪙 {x.stake}</small><em>{x.status}</em></div>)}{!a.length&&<div className="empty">No virtual bets yet.</div>}</div>}
function Games(){return <div className="page"><small>GAME LOUNGE</small><h1>Play Zone</h1><section className="gameHero"><h2>Neon Game Night</h2><p>Arcade-style demo games using virtual coins.</p>✨</section><div className="games">{["🎰 Neon Slots","🎲 Dice Lab","🃏 Card Room","🎯 Spin Arena","🕹️ Retro Rush","🏆 Prize Room"].map(x=><button key={x}><b>{x.split(" ")[0]}</b>{x.slice(2)}<small>Demo game</small></button>)}</div></div>}
function Auth({close,done}){const[m,setM]=useState("login"),[u,setU]=useState(""),[p,setP]=useState(""),[e,setE]=useState("");async function go(){let r=await fetch(m==="login"?"/api/login":"/api/register",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({username:u,password:p})}),d=await r.json();r.ok?done(d.token,d.user):setE(d.error)}return <div className="overlay"><div className="modal"><button className="x"onClick={close}>×</button><div className="authLogo">N</div><small>{m==="login"?"WELCOME BACK":"CREATE ACCOUNT"}</small><h2>{m==="login"?"Login":"Create account"}</h2><input placeholder="Username"value={u}onChange={e=>setU(e.target.value)}/><input placeholder="Password"type="password"value={p}onChange={e=>setP(e.target.value)}/>{e&&<p className="error">{e}</p>}<button className="primary full"onClick={go}>{m==="login"?"Login":"Register"}</button><button className="switch"onClick={()=>setM(m==="login"?"register":"login")}>{m==="login"?"Create an account":"Back to login"}</button></div></div>}
createRoot(document.getElementById("root")).render(<App/>);