import React,{useEffect,useState} from "react"; import {createRoot} from "react-dom/client"; import "./style.css";
const SPORTS=[["cricket","🏏","Cricket"],["tennis","🎾","Tennis"],["football","⚽","Football"],["basketball","🏀","Basketball"]];
const APIKEYS={cricket:"upcoming",tennis:"upcoming",football:"soccer_epl",basketball:"basketball_nba"};
function App(){const [page,setPage]=useState("home"),[user,setUser]=useState(null),[token,setToken]=useState(localStorage.token||""),[coins,setCoins]=useState(0),[sport,setSport]=useState("cricket"),[events,setEvents]=useState([]),[slip,setSlip]=useState([]),[msg,setMsg]=useState("");
useEffect(()=>{if(token)fetch("/api/me",{headers:{Authorization:"Bearer "+token}}).then(r=>r.ok?r.json():null).then(u=>{if(u){setUser(u);setCoins(u.coins)}})},[token]);
const reload=()=>{const s=APIKEYS[sport]; fetch("/api/odds/"+s+"?regions=eu&markets=h2h").then(r=>r.json()).then(d=>setEvents(Array.isArray(d)?d:[])).catch(()=>setEvents([]))};
useEffect(()=>{if(page==="sports")reload()},[page,sport]);
function pick(e,o){setSlip([{eventId:e.id,event:e.home_team+" vs "+e.away_team,selection:o.name,price:o.price}]);setPage("slip")}
async function bet(){if(!user){setPage("login");return} const r=await fetch("/api/bets",{method:"POST",headers:{"Content-Type":"application/json",Authorization:"Bearer "+token},body:JSON.stringify({stake:100,picks:slip})}); const d=await r.json(); if(!r.ok)return setMsg(d.error); setCoins(d.user.coins);setSlip([]);setMsg("Demo bet placed");setPage("bets")}
async function topup(){const r=await fetch("/api/demo-topup",{method:"POST",headers:{Authorization:"Bearer "+token}});const d=await r.json();setCoins(d.coins)}
function logout(){localStorage.removeItem("token");setToken("");setUser(null);setPage("home")}
return <div className="app"><header><button className="logo" onClick={()=>setPage("home")}>NAIDU <i>BOOK</i></button><div className="coins">🪙 {coins.toLocaleString()}</div></header><main>
{page==="home"&&<Home go={setPage} user={user}/>}
{page==="sports"&&<Sports sport={sport} setSport={setSport} events={events} pick={pick} reload={reload}/>}
{page==="slip"&&<Slip slip={slip} bet={bet} msg={msg}/>}
{page==="casino"&&<Casino/>}{page==="bets"&&<History token={token}/>}
{page==="wallet"&&<Wallet user={user} token={token} coins={coins} topup={topup}/>}
{page==="login"&&<Auth setUser={u=>{setUser(u);setCoins(u.coins);setToken(localStorage.token);setPage("home")}}/>}
{page==="profile"&&<Profile user={user} logout={logout}/>}
</main><nav>{[["home","⌂","Home"],["sports","🏏","Sports"],["casino","🎰","Casino"],["wallet","🪙","Wallet"],["profile","👤","Profile"]].map(x=><button className={page===x[0]?"on":""} onClick={()=>setPage(x[0])} key={x[0]}>{x[1]}<small>{x[2]}</small></button>)}</nav></div>}
function Home({go,user}){return <section><div className="hero"><div className="tag">NAIDU BOOK</div><h1>Live Sports & Demo Games</h1><p>Real sports data • Virtual coins • Mobile first</p><button onClick={()=>go("sports")}>Explore Live Sports →</button></div><h2>Sports</h2><div className="cards">{SPORTS.map(s=><button onClick={()=>go("sports")} className="card" key={s[0]}>{s[1]}<b>{s[2]}</b><small>Live & upcoming</small></button>)}</div><h2>Casino Demo</h2><div className="cards">{["🃏 Andar Bahar","🎨 Color Game","🎡 Roulette"].map(x=><button className="card" onClick={()=>go("casino")} key={x}>{x}</button>)}</div><div className="warning">Virtual coins only. No cash deposits, cash withdrawals or cash-value prizes.</div></section>}
function Sports({sport,setSport,events,pick,reload}){return <section><div className="chips">{SPORTS.map(s=><button className={sport===s[0]?"sel":""} onClick={()=>setSport(s[0])} key={s[0]}>{s[1]} {s[2]}</button>)}</div><div className="row"><h2>Live / Upcoming</h2><button className="refresh" onClick={reload}>↻ Refresh</button></div>{!events.length?<div className="empty">No events returned. Configure your sports API key on the server.</div>:events.map(e=><div className="match" key={e.id}><div className="teams"><b>{e.home_team}</b><span>VS</span><b>{e.away_team}</b></div><small>{new Date(e.commence_time).toLocaleString()}</small><div className="odds">{(e.bookmakers?.[0]?.markets?.[0]?.outcomes||[]).map(o=><button onClick={()=>pick(e,o)} key={o.name}><span>{o.name}</span><b>{o.price}</b></button>)}</div></div>)}</section>}
function Slip({slip,bet,msg}){return <section><h2>Demo Bet Slip</h2>{msg&&<div className="warning">{msg}</div>}{!slip.length?<div className="empty">Select a live/upcoming outcome first.</div>:<><div className="match"><b>{slip[0].selection}</b><span className="price">{slip[0].price}</span><small>{slip[0].event}</small></div><div className="summary"><span>Demo stake</span><b>100 coins</b></div><button className="cta" onClick={bet}>Place Demo Bet</button></>}</section>}
function Casino(){const [r,setR]=useState("");const play=g=>setR(g==="Color Game"?["RED","GREEN","VIOLET"][Math.floor(Math.random()*3)]:g==="Andar Bahar"?(Math.random()<.5?"ANDAR":"BAHAR"):["RED","BLACK","GREEN"][Math.floor(Math.random()*3)]);return <section><h2>Casino Demo</h2><p className="muted">Original non-money games.</p><div className="games">{["Andar Bahar","Color Game","Roulette"].map(g=><button onClick={()=>play(g)} key={g}><strong>{g}</strong><small>Play demo</small></button>)}</div>{r&&<div className="result">Result: <b>{r}</b></div>}</section>}
function Auth({setUser}){const [reg,setReg]=useState(false),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[err,setErr]=useState("");async function submit(){const r=await fetch("/api/"+(reg?"register":"login"),{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email,password})});const d=await r.json();if(!r.ok)return setErr(d.error);localStorage.token=d.token;setUser(d.user)}return <section><h2>{reg?"Create account":"Login"}</h2><input placeholder="Email" value={email} onChange={e=>setEmail(e.target.value)}/><input placeholder="Password (6+ chars)" type="password" value={password} onChange={e=>setPassword(e.target.value)}/>{err&&<p className="error">{err}</p>}<button className="cta" onClick={submit}>{reg?"Register":"Login"}</button><button className="link" onClick={()=>setReg(!reg)}>{reg?"Already have an account? Login":"Create a new account"}</button></section>}
function Wallet({user,token,coins,topup}){if(!user)return <section><div className="empty">Login to access your wallet.</div></section>;return <section><h2>Virtual Wallet</h2><div className="balance">🪙 {coins.toLocaleString()}<small>non-redeemable demo coins</small></div><button className="cta" onClick={topup}>Add 1,000 Demo Coins</button><div className="warning">These coins have no cash value and cannot be withdrawn.</div></section>}
function History({token}){const [b,setB]=useState([]);useEffect(()=>{if(token)fetch("/api/bets",{headers:{Authorization:"Bearer "+token}}).then(r=>r.json()).then(setB)},[token]);if(!token)return <section><div className="empty">Login to see demo history.</div></section>;return <section><h2>Demo Bet History</h2>{!b.length?<div className="empty">No demo bets yet.</div>:b.map(x=><div className="match" key={x.id}><b>#{x.id} • {x.stake} coins</b><small>{new Date(x.created_at).toLocaleString()}</small><p>{JSON.parse(x.picks).map(p=>p.selection).join(", ")}</p></div>)}</section>}
function Profile({user,logout}){return <section><h2>Profile</h2>{user?<><div className="match"><b>{user.email}</b><small>Account ID: {user.id}</small></div><button className="cta" onClick={logout}>Logout</button></>:<div className="empty">You are not logged in.</div>}</section>}
createRoot(document.getElementById("root")).render(<App/>);
